// import type { Metadata } from "next";
import ScrollToTopButton from "../../components/ScrollToTopButton";
import "./globals.css";
import Script from "next/script";
import FloatingButton from "../../components/FloatingButton";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="en"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="en-in"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/uae/"
          hrefLang="en-ae"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="x-default"
        />

        <meta
          name="google-site-verification"
          content="CQRj6Bls-OQCYgV4ne5XEQJ8-6KlU7L2JfhusyIuiwM"
        />

        {/* JSON-LD Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "BigWig Digital",
              url: "https://bigwigdigital.in",
              logo: "https://www.bigwigdigital.in/assets/bigwig%20digital%20logo%20(11)-T8_kDtlw.png",
              sameAs: [
                "https://www.facebook.com/bigwigdigital/",
                "https://x.com/bigwig_digital",
                "https://www.instagram.com/bigwig.media.digital",
                "https://www.youtube.com/@BigwigMediaDigital",
                "https://www.linkedin.com/company/bigwig-media-digital/",
                "https://in.pinterest.com/bigwigmediadigital/",
              ],
            }),
          }}
        />

        {/* JSON-LD LocalBusiness */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              name: "BigWig Digital",
              image:
                "https://www.bigwigdigital.in/assets/bigwig%20digital%20logo%20(11)-T8_kDtlw.png",
              url: "https://bigwigdigital.in",
              telephone: "+91 8368573451",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Plot # 2, Sanjay Nagar, Gulabi Bagh",
                addressLocality: "Delhi",
                postalCode: "110007",
                addressCountry: "IN",
              },
              openingHoursSpecification: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                ],
                opens: "11:00",
                closes: "19:30",
              },
            }),
          }}
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body>
        {children}
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2WEBR7ZVN9"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2WEBR7ZVN9');
          `}
        </Script>

        {/* Google Analytics second tag */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-MY747LMT5M"
          strategy="afterInteractive"
        />
        <Script id="google-analytics-2" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-MY747LMT5M');
          `}
        </Script>

        {/* Microsoft Clarity */}
        <Script id="microsoft-clarity" strategy="afterInteractive">
          {`
    (function(c,l,a,r,i,t,y){
      c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
      t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
      y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "v8ibwvlg22");
  `}
        </Script>

        {/* Google Tag Manager */}
        <Script id="gtm" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){
              w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0], j=d.createElement(s), dl=l!='dataLayer'?'&l='+l:'';
              j.async=true; j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
            })(window, document, 'script', 'dataLayer', 'GTM-TMMX5VTN');
          `}
        </Script>

        {/* <!-- Meta Pixel Code --> */}
        <script>
          {`!function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1365940352138121');
            fbq('track', 'PageView');`}
        </script>
        <noscript><img height="1" width="1" style={{ display: "none" }}
          src="https://www.facebook.com/tr?id=1365940352138121&ev=PageView&noscript=1"
        /></noscript>
        {/* <!-- End Meta Pixel Code --> */}

        <FloatingButton />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
